FROM quay.io/fedora/fedora:44

RUN dnf update -y
RUN dnf -y group install development-tools

RUN dnf install -y jq

COPY packages /tmp/
RUN dnf install -y $(cat /tmp/packages | grep "^[^#;]")

RUN dnf clean all

RUN ln -s /usr/bin/fish /usr/local/bin/fish

RUN curl -s -o /usr/local/bin/kubectl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x /usr/local/bin/kubectl && git clone --depth 1 https://github.com/ahmetb/kubectx /opt/kubectx && ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx && ln -s /opt/kubectx/kubens /usr/local/bin/kubens

